### ISSUE TITLE
为什么要令para【1】=4？

### ISSUE THREAD

**Issue by Shutian404** [Harrison-Ho/Analysis-of-2019-nCoV-propagation-based-on-Model#1]
def calculate(func,seri,para,intervene_N):
    steps = 1
    t = np.arange(0,200,steps)
    res=[]
    for itm in t:
        if intervene_N!=0:
            if itm>intervene_N:
                para[0]=4
                **para[1]=4**    应该是paraII吧
        seri=func(seri,para,steps)
        res.append(seri)
    return np.array(res)

**Comment by Harrison-Ho** [comment]
@Shutian404 
Duplicate of 1#

- 不是您注释的paraII，这里函数定义使用的是函数参数para，注意我调用的时候传入的是paraII

- para[0]和para[1]分别表示的是感染者和潜伏者去接触的人。封城措施后，感染者和潜伏者的活动范围受限，该语句强制将其由原来接触20人改为4人。

这个实验还有很大的可探索空间，觉得有用给个star吧
